# Jekyll configuration

name: Ashwin Srinath
description: My experiences learning, writing and teaching software.

# url is currently only used only for the RSS feed in feed.xml
url: http://ashwinsrnth.github.io

# baseurl will usually be ''
baseurl: ''

# This can be '' to hide the Github nav button
github: 'ashwinsrnth'

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
